name: "Setup"
description: "Checkout repository, setup Node.js and PNPM with caching"
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"
        cache: "pnpm"
    - uses: actions/cache@v4
      with:
        path: $(pnpm store path)
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - run: pnpm install
      shell: bash
