services:

  db_keycloak:
    restart: always

  keycloak:
    restart: ${KC_RESTART:-always}
    environment:
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=https://${SERVER_HOST}/auth
      - KC_HOSTNAME_ADMIN=http://localhost:8080
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/certs/${SERVER_HOST}/fullchain.cer
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/certs/${SERVER_HOST}/private.key
      - FRONTEND_URL=https://${SERVER_HOST}
    ports:
      - "8443:8443"
    networks:
      - frontend
    volumes:
      - ./certs:/opt/keycloak/certs:ro
    command: ${KC_CMD:-start --optimized --import-realm}
  
  db:
    restart: always

  hasura:
    restart: always
    environment:
      - HASURA_GRAPHQL_CORS_DOMAIN=https://${SERVER_HOST}
      - HASURA_GRAPHQL_ENABLE_CONSOLE=false
    networks:
      - frontend

  web:
    build: ./keycloak
    restart: always
    depends_on:
      keycloak:
        condition: service_healthy
      hasura:
        condition: service_healthy
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 1s
    environment:
      - SERVER_HOST
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/templates:/etc/nginx/templates:ro

networks:
  frontend:
