name: geyser
services:
  kc-db:
    image: postgres:16
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U postgres -d keycloak || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
      start_interval: 1s
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_KC_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5433:5432"
    networks:
      - private-kc-db
    volumes:
      - kc-data:/var/lib/postgresql/data

  keycloak:
    build: keycloak
    restart: unless-stopped
    depends_on:
      kc-db:
        condition: service_healthy
    healthcheck:
      test: "healthcheck.sh"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 120s
      start_interval: 1s
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: null
      KC_DB_URL: "jdbc:postgresql://kc-db:5432/keycloak"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "${POSTGRES_KC_PASSWORD}"
      KC_DB_SCHEMA: "public"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: "xforwarded"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_DEBUG: "true"
      CLIENT_BACKEND_ROOT_URL: "http://localhost"
      CLIENT_BACKEND_SECRET: null
    ports:
      - "8081:8080"
    networks:
      - private-kc-db
      - public
    volumes:
      - ./backups/realms:/opt/keycloak/data/backups
    command: start --optimized --import-realm

  db:
    image: postgres:16
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U postgres -d geyser || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
      start_interval: 1s
    environment:
      POSTGRES_DB: "geyser"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: null
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    networks:
      - private-db
    volumes:
      - data:/var/lib/postgresql/data
      - ./postgres/init:/initdb
      - ./backups/data:/backups

  hasura:
    image: hasura/graphql-engine:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl -fsS http://localhost:8080/healthz || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
      start_interval: 1s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/geyser"
      HASURA_GRAPHQL_ADMIN_SECRET: null
      HASURA_GRAPHQL_JWT_SECRET: '{"jwk_url":"http://host.docker.internal:3000/.well-known/jwks.json","header":{"type":"Cookie","name":"access_token"},"issuer":"http://localhost/api","audience":"http://localhost/graphql","claims_namespace":"hasura"}'
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "naming_convention"
    ports:
      - "8080:8080"
    networks:
      - private-db
      - public

  nginx:
    image: nginx:latest
    restart: unless-stopped
    # These dependencies are needed for `pnpm run dev`
    # Hasura cannot be healthy until API is started
    depends_on:
      keycloak:
        condition: service_healthy
      hasura:
        condition: service_started
    healthcheck:
      test: "curl -fsS http://localhost/health || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
      start_interval: 1s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      GEYSER_DOMAIN: "localhost"
      NGINX_PROXY_API_URL: "http://host.docker.internal:3000"
      NGINX_PROXY_HASURA_URL: "http://hasura:8080/v1/graphql"
      NGINX_PROXY_KEYCLOAK_URL: "http://keycloak:8080"
      NGINX_PROXY_SPA_URL: "http://host.docker.internal:5173"
    ports:
      - "80:80"
    networks:
      - public
    volumes:
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/includes:/etc/nginx/includes:ro
      - ./client/dist:/usr/share/nginx/html

networks:
  private-db:
  private-kc-db:
  public:

volumes:
  data:
  kc-data:
