services:
  db:
    restart: always

  hasura:
    restart: always
    environment:
      - HASURA_GRAPHQL_CORS_DOMAIN=https://${SERVER_HOST}
      - HASURA_GRAPHQL_ENABLE_CONSOLE=false
  
  kc-db:
    restart: always

  keycloak:
    restart: always
    environment:
      - HASURA_CLIENT_ROOT_URL=https://${SERVER_HOST}
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=https://${SERVER_HOST}/auth
      - KC_HOSTNAME_ADMIN=http://localhost:8081
      - KC_HOSTNAME_DEBUG=false
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/certs/${SERVER_HOST}/fullchain.cer
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/certs/${SERVER_HOST}/private.key
    ports:
      - "8443:8443"
    networks:
      - frontend
    volumes:
      - ./certs:/opt/keycloak/certs:ro
    command: start --optimized --import-realm

  nginx:
    restart: always
    environment:
      - SERVER_HOST
    ports:
      - "443:443"
    volumes: !override
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/templates/https:/etc/nginx/templates:ro
