services:
  backend: !reset []

  hasura:
    depends_on:
      backend: !reset []

  frontend:
    image: nginx:1.27
    depends_on:
      backend: !reset []
      hasura:
        # Hasura cannot be healthy until API is started
        condition: service_started
    environment:
      NGINX_PROXY_API_URL: "http://host.docker.internal:3000"
      NGINX_PROXY_DEV_CLIENT_URL: "http://host.docker.internal:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports: !override
      - "80:80"
    volumes: !override
      - ./nginx/templates/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/includes:/etc/nginx/includes:ro
      - ./client/dist:/usr/share/nginx/html
