name: geyser

services:

  db_keycloak:
    image: postgres:16
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 1s
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$POSTGRES_KC_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - postgres_kc_data:/var/lib/postgresql/data

  keycloak:
    build: ./keycloak
    restart: ${KC_RESTART:-unless-stopped}
    depends_on:
      db_keycloak:
        condition: service_healthy
    healthcheck:
      test: /usr/local/bin/healthcheck
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 1s
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_DB_URL=jdbc:postgresql://db_keycloak:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=$POSTGRES_KC_PASSWORD
      - KC_DB_SCHEMA=public
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - ./keycloak/data/import:/opt/keycloak/data/import
      - ./keycloak/data/import/templates:/opt/keycloak/data/import/templates:ro
    command: ${KC_CMD:-start-dev}

  db:
    image: postgres:16
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 1s
    environment:
      - POSTGRES_DB=geyser
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: curl -fsS http://localhost:8080/healthz || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 1s
    environment:
      - HASURA_GRAPHQL_ADMIN_SECRET
      - HASURA_GRAPHQL_DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/geyser
      - HASURA_GRAPHQL_JWT_SECRET={"jwk_url":"http://keycloak:8080/realms/master/protocol/openid-connect/certs"}
      - HASURA_GRAPHQL_CORS_DOMAIN=*
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    ports:
      - "8090:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_kc_data:
  postgres_data:
