services:
  kc-db:
    restart: always

  keycloak:
    restart: always
    environment:
      KC_HOSTNAME_DEBUG: "false"

  db:
    restart: always

  hasura:
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"

  backend:
    image: ghcr.io/arkandias/geyser-backend:latest
    restart: always

  frontend:
    image: ghcr.io/arkandias/geyser-frontend:latest
    restart: always
