services:
  hasura:
    restart: always
    networks:
      - frontend
  
  keycloak:
    environment:
      - KC_HOSTNAME=http://${SERVER_HOST}/auth
      - KC_HOSTNAME_ADMIN=http://localhost:8081
      - KC_HOSTNAME_DEBUG=true
    networks:
      - frontend
  
  nginx:
    build: ./nginx
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
      hasura:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      start_period: 30s
    environment:
      - SERVER_HOST
    ports:
      - "80:80"
    networks:
      - frontend
    volumes:
      - ./nginx/templates/http:/etc/nginx/templates:ro

networks:
  frontend:
