services:
  nginx:
    build: ./nginx
    restart: always
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 1s
    environment:
      - CLIENT_VERSION=2.0
      - SERVER_HOST
    ports:
      - "80:80"
    networks:
      - frontend
    volumes:
      - ./nginx/templates/http:/etc/nginx/templates:ro

networks:
  frontend:
