services:
  hasura:
    restart: always
    networks:
      - frontend
  
  keycloak:
    networks:
      - frontend
  
  nginx:
    build:
      context: ./nginx
      args:
        - localhost/auth
        - LEGAL_NOTICE
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
      hasura:
        condition: service_healthy
    healthcheck:
      test: service nginx status || exit 1
      start_period: 30s
    environment:
      - CLIENT_VERSION=v0.1
      - SERVER_HOST
    ports:
      - "80:80"
    networks:
      - frontend
    volumes:
      - ./nginx/templates/http:/etc/nginx/templates:ro

networks:
  frontend:
