#!/bin/sh
################################################################################
# Copyright (c) 2024 Julien Hauseux.                                           #
# This file is part of Geyser.                                                 #
# Distributed under the GNU Affero General Public License, version 3.          #
################################################################################

# This script adds Geyser and related environment variables, along with useful
# Docker compose and Hasura aliases, to the configuration file of the detected
# shell (either Bash or Zsh). The additional configurations are designed to
# simplify various operations to administrate and develop Geyser. It must be
# sourced using an interactive shell.

# Set Geyser directory
: "${GEYSER_DIR:=$(realpath "$(dirname "$0")/..")}"

# Add configuration to the interactive shell initialization file
if [ -n "$BASH_VERSION" ]; then
  echo "Shell detected: Bash"
  config_file="$HOME/.bashrc"
elif [ -n "$ZSH_VERSION" ]; then
  echo "Shell detected: Zsh"
  config_file="$HOME/.zshrc"
else
  echo "Unknown shell, configuration not saved"
  exit 0
fi

while true; do
  printf "Select an environment:\n1. Development\n2. Production/Staging\nYour choice: "
  read -r choice
  case $choice in
    1 ) echo "You chose Development";
      GEYSER_MODE=development
      gcompose='docker compose --env-file "$GEYSER_DIR"/.env.dev --env-file "$GEYSER_DIR"/.env.local -f "$GEYSER_DIR"/compose.yaml'
      break;;
    2 ) echo "You chose Production/Staging";
      GEYSER_MODE=production
      gcompose='docker compose --env-file "$GEYSER_DIR"/.env.prod --env-file "$GEYSER_DIR"/.env.local -f "$GEYSER_DIR"/compose.yaml -f "$GEYSER_DIR"/compose.prod.yaml'
      break;;
    * ) echo "Not a valid choice";;
  esac
done

sed_i () {
  OS=$(uname)
  case "$OS" in
    "Linux")
      sed -i "$@"
      ;;
    "Darwin")
      sed -i '' "$@"
      ;;
    *)
      echo "Unknown OS, configuration not saved"
      exit 0
      ;;
  esac
}

config=$(cat << EOF
# BEGIN Geyser configuration
export GEYSER_DIR="$GEYSER_DIR"
export GEYSER_MODE="$GEYSER_MODE"
alias geyser='\$GEYSER_DIR/scripts/geyser'
alias gcompose="$gcompose"
alias ghasura='source "\$GEYSER_DIR"/.env.local && export HASURA_GRAPHQL_ADMIN_SECRET && hasura --project "\$GEYSER_DIR"/hasura'
alias grsync='rsync -rlv --delete --files-from="\$GEYSER_DIR"/rsync-files --exclude-from="\$GEYSER_DIR"/rsync-exclude "\$GEYSER_DIR"/'
#source \$GEYSER_DIR/scripts/_complete_kc
# END Geyser configuration
EOF
)

echo "The following configuration will be added to ${config_file} (previous configurations will be removed):"
echo "$config"

sed_i '/# BEGIN Geyser configuration/,/# END Geyser configuration/d' "$config_file"
while [ "$(tail -n 1 "$config_file" | grep -v '^$')" = "" ]; do
  sed_i -e '$d' "$config_file"
done
{
  echo ""
  echo "$config"
  echo ""
} >> "$config_file"
