#!/bin/sh
# This script is intended to be sourced using an interactive shell (either Bash
# or Zsh). It adds some environment variables along with some useful aliases to
# the configuration file of the detected shell. These configurations are
# designed to simplify various operations to administrate Geyser.

# Detect current shell
if [ -n "${BASH_VERSION}" ]; then
    echo "Shell detected: Bash"
    config_file="${HOME}/.bashrc"
elif [ -n "${ZSH_VERSION}" ]; then
    echo "Shell detected: Zsh"
    config_file="${HOME}/.zshrc"
else
    echo "Unknown shell, configuration not saved"
    exit 0
fi

# Set Geyser directory
default_dir="$(cd "$(dirname "$0")"/.. && pwd)"
printf "Geyser installation directory [%s]: " "${default_dir}"
read -r install_dir
GEYSER_DIR=${install_dir:-$default_dir}

# Set Geyser mode
printf "Select an environment:\n1) Development\n2) Production/Staging\n"
while true; do
    printf "Your choice: "
    read -r choice
    case $choice in
    1)
        GEYSER_MODE=development
        # shellcheck disable=SC2016
        gcompose='docker compose --env-file "${GEYSER_DIR}"/.env --env-file "${GEYSER_DIR}"/.env.development --env-file "${GEYSER_DIR}"/.env.local --env-file "${GEYSER_DIR}"/.env.development.local -f "${GEYSER_DIR}"/compose.yaml'
        break
        ;;
    2)
        GEYSER_MODE=production
        # shellcheck disable=SC2016
        gcompose='docker compose --env-file "${GEYSER_DIR}"/.env --env-file "${GEYSER_DIR}"/.env.production --env-file "${GEYSER_DIR}"/.env.local --env-file "${GEYSER_DIR}"/.env.production.local -f "${GEYSER_DIR}"/compose.yaml -f "${GEYSER_DIR}"/compose.prod.yaml'
        break
        ;;
    *) echo "Not a valid choice" ;;
    esac
done

sed_i() {
    OS=$(uname)
    case "$OS" in
    "Linux")
        sed -i "$@"
        ;;
    "Darwin")
        sed -i '' "$@"
        ;;
    *)
        echo "Unknown OS, configuration not saved"
        exit 0
        ;;
    esac
}

# The configuration
config=$(
    cat <<EOF
# BEGIN Geyser configuration
export GEYSER_DIR="${GEYSER_DIR}"
export GEYSER_MODE="${GEYSER_MODE}"
alias geyser='\${GEYSER_DIR}/geyser'
alias gcompose="$gcompose"
alias ghasura='source "\${GEYSER_DIR}"/.env.local && export HASURA_GRAPHQL_ADMIN_SECRET && hasura --project "\${GEYSER_DIR}"/hasura'
alias grsync='rsync -rlv --delete --files-from="\${GEYSER_DIR}"/rsync-files --exclude-from="\${GEYSER_DIR}"/rsync-exclude "\${GEYSER_DIR}"/'
# END Geyser configuration
EOF
)

echo "Configuration:"
echo "$config"
while true; do
    printf "Add to %s? [Y/n] " "$config_file"
    read -r choice
    case $choice in
    "" | y | Y)
        sed_i '/# BEGIN Geyser configuration/,/# END Geyser configuration/d' "$config_file"
        while [ "$(tail -n 1 "$config_file" | grep -v '^$')" = "" ]; do
            # shellcheck disable=SC2016
            sed_i -e '$d' "$config_file"
        done
        {
            echo ""
            echo "$config"
            echo ""
        } >>"$config_file"
        break
        ;;
    n | N) break ;;
    *) echo "Not a valid choice" ;;
    esac
done

# Completion
echo "Install Geyser completion for:"
echo "1) Bash"
echo "2) Zsh (using oh-my-zsh)"
echo "3) None"
read -r selection
case "$selection" in
1)
    cp "${GEYSER_DIR}"/scripts/completion/geyser-completion.bash /etc/bash_completion.d/geyser
    ;;
2)
    mkdir -p "$HOME"/.oh-my-zsh/completions
    cp "${GEYSER_DIR}"/scripts/completion/_geyser "$HOME"/.oh-my-zsh/completions/_geyser
    ;;
3) ;;

*)
    echo "Invalid option"
    ;;
esac
