#!/bin/bash
################################################################################
# Copyright (c) 2024 Julien Hauseux.                                           #
# This file is part of Geyser.                                                 #
# Distributed under the GNU Affero General Public License, version 3.          #
################################################################################

# This script dumps the 'geyser' database and uploads the backup to a remote
# Nextcloud server. It is intended to be scheduled via crontab for regular 
# execution.

: "${GEYSER_DIR:=$(dirname "$0")/..}"

source "$GEYSER_DIR"/.env.local
export PGPASSWORD="$POSTGRES_PASSWORD"

timestamp=$(date +%Y-%m-%d-%H-%M-%S)
filename="db_geyser_${timestamp}"
filepath="${GEYSER_DIR}/backups/${filename}.dump"

"$GEYSER_DIR"/scripts/db dump --file="$filepath"
hash=$(sha256sum "$filepath")

echo "Uploading backup..."
curl -u "${NEXTCLOUD_USER}:${NEXTCLOUD_PASS}" -T "$filepath" "${NEXTCLOUD_URL}/remote.php/dav/files/${NEXTCLOUD_USER}/geyser/backups/${filename}_${hash}.dump"
echo "Done"
