#!/bin/bash
# This script is a shorthand to run Docker Compose commands with the environment
# corresponding to $GEYSER_MODE (development or production).

: "${GEYSER_DIR:=$(dirname "$0")/..}"

if [[ $GEYSER_MODE == "production" ]]; then
    docker compose --env-file "$GEYSER_DIR"/.env.prod --env-file "$GEYSER_DIR"/.env.local -f "$GEYSER_DIR"/compose.yaml -f "$GEYSER_DIR"/compose.prod.yaml "$@"
elif [[ $GEYSER_MODE == "development" ]]; then
    docker compose --env-file "$GEYSER_DIR"/.env.dev --env-file "$GEYSER_DIR"/.env.local -f "$GEYSER_DIR"/compose.yaml "$@"
else
    echo "Error: GEYSER_MODE must be set to 'development' or 'production'" >&2
    exit 1
fi
