#!/bin/bash
################################################################################
# Copyright (c) 2024 Julien Hauseux.                                           #
# This file is part of Geyser.                                                 #
# Distributed under the GNU Affero General Public License, version 3.          #
################################################################################

# This script provides command-line interactions for database management for the 
# Geyser project, this includes initialization, cleaning, restoration, and 
# dumping of the database or specific database schemas.
# 
# Usage: db COMMAND [OPTIONS]
# 
# Commands:
#   init        Initialize the database with predefined SQL scripts.
#   clean       Clean the entire database or the schema specified by the --schema option.
#   dump        Create a complete dump of the database or the schema specified by the --schema option.
#   restore     Restore the database or the schema specified by the --schema option from a dump file.
# 
# Options:
#   --schema=<schema_name>    Specifies the database schema to interact with.
#   --file=<file_path>        Specifies the file to be used with dump/restore.
# 
# Note: All commands access the PostgreSQL database `geyser` hosted on 
# `localhost:5432` using the `postgres` user. The password for `postgres` is 
# obtained from the `.env.local` file.

# Exit script on any error
set -e

: "${GEYSER_DIR:=$(dirname "$0")/..}"

source "$GEYSER_DIR"/.env.local
export PGPASSWORD="$POSTGRES_PASSWORD"

valid_identifier () {
  if [[ ! $1 =~ ^[_a-zA-Z][_a-zA-Z0-9]*$ ]]; then
    echo "Error: Invalid identifier $1" >&2
    exit 1
  fi
  echo "$1"
}

# Options
schema=""
file=""
for arg in "$@"; do
  shift
  case "$arg" in
    --schema=*)
      IFS="=" read -ra parts <<< "$arg"
      schema=$(valid_identifier "${parts[1]}")
      ;;
    --file=*)
      IFS="=" read -ra parts <<< "$arg"
      file="${parts[1]}"
      ;;
    --*)
      echo "Warning: Unknown option $arg ignored" >&2
      ;;
    *)
      set -- "$@" "$arg"
      ;;
  esac
done

ignore_extra_args () {
  shift
  local arg
  for arg in "$@"; do
    echo "Warning: Extra command-line argument $arg ignored" >&2
    shift
  done
}

init () {
  source "$GEYSER_DIR"/.env.local
  export KC_DB_PASSWORD HASURA_DB_PASSWORD
  echo "Initializing database..."
  find "$GEYSER_DIR"/postgres/initdb/*.sql -type f -print0 | xargs -0 -n 1 psql -U postgres -h localhost -p 5432 -d geyser -v ON_ERROR_STOP=1 -f >/dev/null
  echo "Done"
  exit 0
}

clean () {
  if [[ -z "$schema" ]]; then
    echo "Cleaning database..."
    psql -U postgres -h localhost -p 5432 >/dev/null <<-EOSQL
		DROP DATABASE IF EXISTS geyser WITH (FORCE);
		CREATE DATABASE geyser;
		EOSQL
    echo "Done"
  else
    echo "Cleaning schema $schema..."
    psql -U postgres -h localhost -p 5432 -d geyser >/dev/null <<-EOSQL
		DROP SCHEMA IF EXISTS ${schema} CASCADE;
		CREATE SCHEMA ${schema};
		EOSQL
    echo "Done"
  fi
}

dump () {
  if [[ -z "$schema" ]]; then
    echo "Dumping database..."
    if [[ -z "$file" ]]; then
      mkdir -p "$GEYSER_DIR/backups"
      file="$GEYSER_DIR/backups/db_geyser_$(date +%Y-%m-%d-%H-%M-%S).dump"
    fi
    pg_dump -U postgres -h localhost -p 5432 -d geyser -Fc -f "$file"
    echo "Done"
  else
    echo "Dumping schema $schema..."
    if [[ -z "$file" ]]; then
      mkdir -p "$GEYSER_DIR/backups"
      file="$GEYSER_DIR/backups/schema_${schema}_$(date +%Y-%m-%d-%H-%M-%S).dump"
    fi
    pg_dump -U postgres -h localhost -p 5432 -d geyser -n "$schema" -Fc -f "$file"
    echo "Done"
  fi
}

select_backup () {
  cd "$GEYSER_DIR"/backups || exit 1
  shopt -s nullglob
  if [[ -z "$schema" ]]; then
    files=(db_geyser_*.dump)
  else
    files=(schema_"$schema"_*.dump)
  fi
  shopt -u nullglob
  if [[ ${#files[@]} -eq 0 ]]; then
    echo "No backup found"
    exit 1
  fi
  echo "Select a backup:"
  select file in "${files[@]}"; do
    break
  done
}

restore () {
  if [[ -n "$file" ]]; then
    if [[ ! -f "$file"  ]]; then
      echo "Error: File $file does not exists" >&2
      exit 1
    fi
  else
    if ! select_backup; then
      echo "$file"
      exit 1
    fi
  fi
  if [[ -z "$schema" ]]; then
    echo "Restoring database..."
    pg_restore -U postgres -h localhost -p 5432 -d geyser -1 "$file"
    echo "Done"
  else
    echo "Restoring schema $schema..."
    pg_restore -U postgres -h localhost -p 5432 -d geyser -1 -n "$schema" "$file"
    echo "Done"
  fi
}

# Actions
ignore_extra_args "$@"
case $1 in
  init)
    if [[ -n "$schema" ]]; then
      echo "Warning: Option --schema ignored for action init" >&2
    fi
    if [[ -n "$file" ]]; then
      echo "Warning: Option --file ignored for action init" >&2
    fi
    init
    ;;
  clean)
    if [[ -n "$file" ]]; then
      echo "Warning: Option --file ignored for action clean" >&2
    fi
    clean
    ;;
  dump)
    dump
    ;;
  restore)
    restore
    ;;
  *)
    echo "Usage: db {clean|dump|init|restore}"
    exit 0
    ;;
esac
