#!/bin/bash
# This script exports the attributions of a given year into multiple CSV files,
# one per mention.

: "${GEYSER_DIR:=$(dirname "$0")/..}"

source "${GEYSER_DIR}"/.env.local
export PGPASSWORD="${POSTGRES_PASSWORD}"

if [[ -z "$1" ]]; then
    echo "You must provide the year for the exports" >&2
    exit 1
fi

annee="$1"
shift
for arg in "$@"; do
    echo "Warning: Extra command-line argument $arg ignored" >&2
    shift
done

mkdir -p "${GEYSER_DIR}"/attributions

filename="${annee}_$(date +"%Y%m%d_%H%M%S")"

query_attributions=$(
    cat <<-EOSQL
  SELECT c.nom as cursus, m.nom as mention, p.nom as parcours, e.semestre, e.nom as enseignement, e.type, i.nom, i.prenom, i.uid as email, d.heures, round((d.heures / e.heures)::numeric, 2) as groupes
  FROM demande d
    JOIN intervenant i ON d.uid = i.uid
    JOIN enseignement e ON d.ens_id = e.id
    JOIN mention m ON e.mention_id = m.id
    JOIN cursus c ON m.cursus_id = c.id
    LEFT JOIN parcours p ON e.parcours_id = p.id
  WHERE e.annee = ${annee} AND d.type = 'attribution'
  ORDER BY c.nom, m.nom, p.nom, e.semestre, e.nom, e.type, i.nom, i.prenom
EOSQL
)
psql -U postgres -h localhost -p 5432 -d geyser -c "COPY (${query_attributions}) TO STDOUT WITH CSV HEADER" >"${GEYSER_DIR}/attributions/${filename}.csv"
