#!/bin/bash

# This script provides some commands to manage the Geyser server.
#
# Usage: geyser COMMAND [OPTIONS]
#
# Commands:
#   init        Initialize Geyser.
#   start       Start Geyser containers.
#   stop        Stop Geyser containers.
#   restart     Restart Geyser containers (equivalent to stop then start).
#   update      Update Geyser containers (pull and build images).
#   reset       Start a fresh configuration.
#   backup      Backup the current configuration.
#   restore     Restore a configuration among a list of backups.
#
# Options:
#   --dev       Specifies the development configuration.
#   --prod      Specifies the production/staging configuration.

# Exit script on any error
set -e

: "${GEYSER_DIR:=$(dirname "$0")/..}"

# Options
for arg in "$@"; do
    shift
    case "$arg" in
    --dev)
        GEYSER_MODE=development
        ;;
    --prod)
        GEYSER_MODE=production
        ;;
    --*)
        echo "Warning: Unknown option $arg ignored" >&2
        ;;
    *)
        set -- "$@" "$arg"
        ;;
    esac
done
if [[ "$GEYSER_MODE" != 'development' ]] && [[ "$GEYSER_MODE" != 'production' ]]; then
    echo "Error: the mode (development/production) must be set, using either \
        options --dev/--prod, or the environment variable GEYSER_MODE" >&2
    exit 1
fi
export GEYSER_MODE

ignore_extra_args() {
    shift
    local arg
    for arg in "$@"; do
        echo "Warning: Extra command-line argument '$arg' ignored" >&2
        shift
    done
}

wait_until_healthy() {
    echo "Waiting for service $1 to become healthy..."
    local health
    health=$("$GEYSER_DIR"/scripts/compose ps "$1" --format json | jq '.Health')
    while [[ "$health" != "\"healthy\"" ]]; do
        if [[ "$health" == "\"unhealthy\"" ]]; then
            echo "Error: Service $1 is unhealthy" >&2
            exit 1
        fi
        if [[ -z "$health" ]]; then
            echo "Error: Service $1 stopped" >&2
            exit 1
        fi
        sleep 1
        health=$("$GEYSER_DIR"/scripts/compose ps "$1" --format json | jq '.Health')
    done
    echo "Done"
}

wait_until_exit() {
    echo "Waiting for service $1 to exit..."
    while [[ -n $("$GEYSER_DIR"/scripts/compose ps -q "$1") ]]; do
        sleep 1
    done
    container_id=$("$GEYSER_DIR"/scripts/compose ps -aq "$1")
    if [[ -n "$container_id" ]]; then
        exit_code=$(docker inspect --format='{{.State.ExitCode}}' "${container_id}")
    fi
    if [[ $exit_code -eq 0 ]]; then
        echo "Done"
    else
        echo "Warning: $1 exited with code $exit_code" >&2
    fi
}

# Actions
ignore_extra_args "$@"
case $1 in
init)
    "$GEYSER_DIR"/scripts/compose up -d keycloak
    wait_until_healthy keycloak
    "$GEYSER_DIR"/scripts/kcadm --login
    "$GEYSER_DIR"/scripts/kcadm update realms/master -s attributes.frontendUrl=http://localhost:8080
    "$GEYSER_DIR"/scripts/compose up -d
    wait_until_healthy hasura
    "$GEYSER_DIR"/scripts/hasura migrate apply --database-name default
    "$GEYSER_DIR"/scripts/hasura seed apply --database-name default
    "$GEYSER_DIR"/scripts/hasura metadata apply
    ;;
start)
    if ! docker volume inspect geyser_data_keycloak >/dev/null 2>&1; then
        echo "Volume 'geyser_data_keycloak' does not exists. You must initialize Geyser first"
        exit 1
    fi
    if ! docker volume inspect geyser_data >/dev/null 2>&1; then
        echo "Volume 'geyser_data' does not exists. You must initialize Geyser first"
        exit 1
    fi
    "$GEYSER_DIR"/scripts/compose up -d
    ;;
stop)
    "$GEYSER_DIR"/scripts/compose down
    ;;
restart)
    "$GEYSER_DIR"/scripts/compose down
    "$GEYSER_DIR"/scripts/compose up -d
    ;;
update)
    "$GEYSER_DIR"/scripts/compose pull
    "$GEYSER_DIR"/scripts/compose build
    echo "Geyser has been updated. You must now restart Geyser"
    ;;
reset)
    "$GEYSER_DIR"/scripts/compose down -v
    echo "Geyser has been reset. You must now initialize Geyser"
    ;;
backup)
    date="$(date +%Y-%m-%d-%H-%M-%S)"
    "$GEYSER_DIR"/scripts/kc_run export --dir "/opt/keycloak/data/backups/${date}/" --realm geyser
    "$GEYSER_DIR"/scripts/compose exec -e PGPASSWORD=postgres_pwd db \
        pg_dump -U postgres -h localhost -p 5432 -d geyser -Fc -f "/backups/geyser_${date}.dump"
    ;;
restore)
    # Stop Geyser and enable nullglob
    "$GEYSER_DIR"/scripts/compose down
    shopt -s nullglob
    # Keycloak
    dir_paths=("$GEYSER_DIR"/keycloak/backups/*/)
    if [[ ${#dir_paths[@]} -eq 0 ]]; then
        echo "No backup found. Skipping"
    else
        dir_names=()
        for path in "${dir_paths[@]}"; do
            dir_names+=("$(basename "${path%/}")")
        done
        echo "Choose a backup for Keycloak (enter 0 to skip):"
        select name in "${dir_names[@]}"; do
            if [ -n "$name" ]; then
                "$GEYSER_DIR"/scripts/kc_run import --dir /opt/keycloak/data/backups/"$name"/
                break
            else
                echo "No backup selected. Skipping"
                break
            fi
        done
    fi
    # Geyser
    file_paths=("$GEYSER_DIR"/backups/geyser_*.dump)
    if [[ ${#file_paths[@]} -eq 0 ]]; then
        echo "No backup found. Skipping"
    else
        file_names=()
        for path in "${file_paths[@]}"; do
            file_names+=("$(basename "${path%/}")")
        done
        echo "Choose a backup for Geyser (enter 0 to skip):"
        select name in "${file_names[@]}"; do
            if [ -n "$name" ]; then
                "$GEYSER_DIR"/scripts/compose up -d db
                wait_until_healthy db
                "$GEYSER_DIR"/scripts/compose exec -e PGPASSWORD=postgres_pwd db \
                    pg_restore -U postgres -h localhost -p 5432 -d geyser --clean --if-exists -1 /backups/"$name"
                break
            else
                echo "No backup selected. Skipping"
                break
            fi
        done
    fi
    # Disable nullglob and restart Geyser
    shopt -u nullglob
    "$GEYSER_DIR"/scripts/compose up -d
    ;;
*)
    echo "Usage: geyser {init|start|stop|restart|update|reset|save|restore}"
    ;;
esac
