#!/bin/bash
# This script is less of an installation script and more of a checklist of all
# the tools that one should install on a server to run and administer Geyser.

# Check if system is running on Ubuntu
if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    if [[ "$ID" = "ubuntu" ]]; then
        echo "System is running on Ubuntu. Starting installation"
    else
        echo "System is not running on Ubuntu. Exiting installation"
        exit 1
    fi
else
    echo "System is not running on Ubuntu. Exiting installation"
    exit 1
fi

# Docker
## Uninstall old versions:
for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
    sudo apt-get remove $pkg
done

## Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

## Add the repository to Apt sources:
echo "deb [arch=$(dpkg --print-architecture) \
signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/ubuntu \
$(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
    sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
sudo apt-get update

## Install the latest version:
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

## Manage Docker as a non-root user:
sudo groupadd docker
sudo usermod -aG docker "$USER"
newgrp docker

## Configure Docker to start on boot:
sudo systemctl enable docker.service
sudo systemctl enable containerd.service

# PostgreSQL
## Automated repository configuration:
sudo apt install -y postgresql-common
sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh

## Installation:
sudo apt-get install postgresql-16

# jq
sudo apt-get install jq

# Hasura CLI
## Install:
curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

# Completion
echo "Install Docker and Hasura completion for:"
echo "1) Bash"
echo "2) Zsh (using oh-my-zsh)"
echo "3) None"
read -r selection
case "$selection" in
1)
    sudo apt install bash-completion
    echo docker completion bash | sudo tee /etc/bash_completion.d/docker >/dev/null
    echo hasura completion bash | sudo tee /etc/bash_completion.d/hasura >/dev/null
    ;;
2)
    mkdir -p "$HOME"/.oh-my-zsh/completions
    docker completion zsh >"$HOME"/.oh-my-zsh/completions/_docker
    hasura completion zsh >"$HOME"/.oh-my-zsh/completions/_hasura
    ;;
3)
    exit 0
    ;;
*)
    echo "Invalid option"
    ;;
esac
