#!/bin/bash
################################################################################
# Copyright (c) 2024 Julien Hauseux.                                           #
# This file is part of Geyser.                                                 #
# Distributed under the GNU Affero General Public License, version 3.          #
################################################################################

# This script is a shorthand to execute a Keycloak command on a running Keycloak
# instance.

: "${GEYSER_DIR:=$(dirname "$0")/..}"

"$GEYSER_DIR"/scripts/compose exec keycloak /opt/keycloak/bin/kc.sh "$@"
