#!/bin/bash
# This script is a shorthand for synchronizing a local Geyser directory to a
# remote server.

: "${GEYSER_DIR:=$(dirname "$0")/..}"

rsync -rlv --delete --files-from="$GEYSER_DIR"/rsync-files --exclude-from="$GEYSER_DIR"/rsync-exclude "$GEYSER_DIR"/ "$@"
