name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "*"

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_type == 'branch' }}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Format check with Prettier
        run: pnpm run format:check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run tests with Vitest
        run: pnpm run test

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Type check with TypeScript
        run: pnpm run typecheck

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint with ESLint
        run: pnpm run lint

  release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: [format, test, typecheck, lint]
    steps:
      - name: Check if tag matches version pattern
        id: check_tag
        run: |
          TAG_NAME=${{ github.ref_name }}
          if [[ $TAG_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9.]+)?$ ]]; then
            VERSION=${TAG_NAME#v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "✅ Tag matches version pattern: $TAG_NAME -> $VERSION"
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "❌ Tag does not match version pattern: $TAG_NAME"
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create GitHub Release
        if: steps.check_tag.outputs.should_release == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG_NAME="${{ github.ref_name }}"
          PRERELEASE_FLAG=""

          # Check if tag contains prerelease keywords
          if [[ $TAG_NAME =~ -(alpha|beta|rc) ]]; then
            PRERELEASE_FLAG="--prerelease"
          fi

          gh release create ${{ github.ref_name }} \
            --title "${{ steps.check_tag.outputs.version }}" \
            --generate-notes \
            $PRERELEASE_FLAG
